### ISSUE TITLE
[typescript] Can't resolve 'fs' when running `expect(() => throw 'error').toThrow()`

### ISSUE THREAD

**Issue by howtimeflies-io** [phongnd39/cypress-jest-adapter#1]
Hi @phongnd39 
Thank you for this adapter library. It works great when writing integration tests with Javascript.

But unfortunately, it fails with Typescript. Could you please check it?

### Repository to reproduce: 
https://github.com/howtimeflies-io/cypress-jest-adapter-typescript-issue

### Steps:
* `yarn install`
* `yarn cy:run`

### Problem:
```
  Running: simple.e2e.ts...                                                                (1 of 1) 

Oops...we found an error preparing this test file:

  cypress/support/index.js

The error was:

./node_modules/cypress-jest-adapter/dist/index.js
Module not found: Error: Can't resolve 'fs' in 'cypress-jest-adapter-issue/node_modules/cypress-jest-adapter/dist'
resolve 'fs' in 'cypress-jest-adapter-issue/node_modules/cypress-jest-adapter/dist'
  Parsed request is a module
  using description file: cypress-jest-adapter-issue/node_modules/cypress-jest-adapter/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
...
```

**Comment by phongnd39** [comment]
@howtimeflies-io thanks for raising issue and create a pull request. I have updated this package to npm registry, and updated the example for typescript and it should work fine by now.

**Comment by howtimeflies-io** [comment]
@phongnd39 The latest version works in Typescript. Thank you.
