### ISSUE TITLE
Typings don't work - all asertions are `any`

### ISSUE THREAD

**Issue by danantal** [phongnd39/cypress-jest-adapter#4]
I have cloned the repository and tried to run the typescript examples.

However, the typings for the jest style assertions evaluate as `any`; https://cl.ly/e0082036630d

I'm using VS Code... and typescript version from the node_modules.

However, I can see the `index.d.ts` file is present in `node_modules/cypress-jest-adapter` - but it's not working as expected.

**Comment by phongnd39** [comment]
Thanks for reporting the issue.
i just take a quick look on this in vscode and a quick solutions is to add 
```
/// <reference types="cypress" /> 
```
to the head of the test file and it seems to be solved.

I will check more about this issue and update the example later

**Comment by danantal** [comment]
Thanks for the quick reply - Indeed it does work 👍 

I am thinking that moving `index.d.ts` it out to `@types` could be a good idea anyway.. but not sure why it would break the Cypress typings. Apparently also `expect` is identified as `any` when the jest assertions is installed.
