### ISSUE TITLE
Add `toAsymmetricMatcher` to async matchers 

### ISSUE THREAD

**Issue by shinjini-saha** [phongnd39/cypress-jest-adapter#5]
I was trying to add my own custom matchers and wanted to leverage `diff`, `printExpected`, `printReceived` from `jest-matcher-utils`, but I get an error:

```
val.toAsymmetricMatcher is not a function
```

The solution is to add `toAsymmetricMatcher` to the async matchers the same way `toString`  is added.

**Comment by phongnd39** [comment]
Thanks for submit a ticket.
Can you describe how you added your custom matcher so that i can reproduce the error you got?
Thanks

**Comment by shinjini-saha** [comment]
> Thanks for submit a ticket.
> Can you describe how you added your custom matcher so that i can reproduce the error you got?
> Thanks

Example matcher code (using the toMatchObject matcher as an example here, my actual matcher was a bit more complex):

```js
import * as matcherUtils from "jest-matcher-utils"
import { getObjectSubset, iterableEquality, subsetEquality } from "expect/build/utils"
import { equals } from "expect/build/jasmineUtils"

function toMatchObjectHelper(received, expected) {
  const matcherName = "toMatchObject"
  const options = {
    isNot: this.isNot,
    promise: this.promise,
  }

  const matcherHint = matcherUtils.matcherHint(matcherName, undefined, undefined, options)

  // These are from the actual toMatchObject matcher.
  const pass = equals(received, expected, [iterableEquality, subsetEquality])
  const difference = matcherUtils.diff(expected, getObjectSubset(received, expected))

  return {
    pass,
    message: () => {
      return (
        `${matcherHint}\n\n` +
        `Expected ${matcherUtils.printReceived(received)} ` +
        `${this.isNot ? "not " : ""}` +
        `to match object ${matcherUtils.printExpected(expected)}` +
        `${!pass && difference ? `\nDifference:\n${difference}` : ""}`
      )
    },
  }
}


chai.use((_chai, utils) => {
  const { Assertion } = chai

  const jestMatcherThis = _this => {
    const not = !!utils.flag(_this, "negate")
    return { isNot: not, promise: "" }
  }

  Assertion.addMethod("toMatchObject", function toMatchObject(expected) {
    const received = utils.flag(this, "object")

    const { pass, message: getMessage } = toMatchObjectHelper.call(jestMatcherThis(this), received, expected)
    const failureMessage = getMessage()
    this.assert(pass, failureMessage, failureMessage)
  })
})
```

Test that results in an error:
```js
expect({ test: 2 }).toMatchObject({ test: expect.stringMatching("ab") })
// val.toAsymmetricMatcher is not a function
```

**Comment by shinjini-saha** [comment]
To add a bit of context, my custom matcher is written this way (with a helper returning `{ pass, message }`) because I also use it in my jest tests and this lets me minimize code duplication.

**Comment by phongnd39** [comment]
I see what you are trying to do here. It seems jest-matching-utils using the result of toString to decide what to print to the console screen, so i stop overriding this toString method and you should be able to use the setup you want :)
I just create an update to npm. Please try updating it and let me know if you have any issue with this

**Comment by shinjini-saha** [comment]
Thank you! I am no longer having this issue.
